version: '3.5'

services:
  v2ray:
    image: v2ray/official:latest
    container_name: v2ray_server
    restart: always
    volumes:
      - ./v2ray:/etc/v2ray
    ports:
      - "16823:16823"
    command: ["v2ray","-config=/etc/v2ray/config_sever.json"]